### ISSUE TITLE
Newest FDroid release crashes

### ISSUE THREAD

**Issue by UltraBlackLinux** [beat-feet/beat-feet#108]
Yes, it just dies. I can't get the logs as magisk currently bootloops my device.

welp that one guy managed to fix it but closed the issue? Okay

**Comment by mus1c-123** [comment]
I ran into the same issue with version 0.12.1

**Comment by pserwylo** [comment]
Thanks for the report all. I can confirm that 0.12.2 was just released on F-Droid a few moments ago, and should address this crashing issue. I'll close this, but feel free to re-open if the problem persists.
