### ISSUE TITLE
Character strings are just white rectangles in device with Farsi language

### ISSUE THREAD

**Issue by doondoondoondoon** [beat-feet/beat-feet#112]
My phone's language is set to Farsi, when I open the game no strings are shown, just rectangles:

![Screenshot_۲۰۲۱۰۸۲۹-۱۳۰۸۴۰_beat-game](https://user-images.githubusercontent.com/89726494/131244886-524af713-06be-413b-b257-5a303a1171d0.png)

This didn't happen in earlier versions when Farsi wasn't available, or when my phone's language is set to English (characters are shown in English).
Is it possible for now until rtl languages issue is fixed to disable Farsi so game strings shown in English?
Or an option to choose language in the game? (also this would be a problem when every string is just a white rectangle.)

Android version: 8
game version: 0.12.2
Device language: Farsi

**Comment by pserwylo** [comment]
Oooh, great pickup, thanks for reporting and including a screenshot!

I've put together a fix in PR #113 which correctly falls back to English. I'll push a release out in the coming days, which will get built by F-Droid in the next week or so. Once released there, I'll also release to Google Play.

Also, thank you for your understanding with regards to RTL languages not being supported. I'd really love this to get working for you, but it is not a strength of mine, so I am at the whim of the libgdx community while they work through a solution. I will periodically check to see if a solution exists, but I am not holding my breath unfortunately :( Fingers crossed though!
