### ISSUE TITLE
Support FLAC?

### ISSUE THREAD

**Issue by sexynos300** [beat-feet/beat-feet#120]
Hi guys, add please support flac codec

**Comment by pserwylo** [comment]
Thank you for the suggestion. I'd love to support the widest range of formats possible, but unfortunately the framework we are using (libgdx) only supports [MP3](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/Mp3.java) and [OGG](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/Ogg.java) at this point. It may be possible to hack the engine to support other file formats, and any pull requests to achieve this would be more than welcome (not just by this game, but also no doubt others who use the libgdx framework).

As I don't have the ability to do this currently, I'll close this issue for now, but please feel free to reopen yourself, or anybody else, if you can see a way to get libgdx to play Flac media.
