### ISSUE TITLE
Crashes in About if network is not available

### ISSUE THREAD

**Issue by davidmef** [beat-feet/beat-feet#132]
Beat Feet 0.14.3.

1. I cut the Internet access for the program
2. I open the application and press the About button
3. After a while of "Loading", the app crashes.

I suggest that, if network is not available, it should inform the user and return to the main menu.

**Comment by pserwylo** [comment]
A belated thank you for this report. I've not had a lot of time to work on projects lately, but have returned to continue working on these. This is one of the first bugs on the list, should be fixed in Version 0.14.6 which I've just tagged and F-Droid should build in within a week or so.
