### ISSUE TITLE
.opus support

### ISSUE THREAD

**Issue by RustoMCSpit** [beat-feet/beat-feet#147]

**Comment by pserwylo** [comment]
Hi there, thanks for the request. Unfortunately this is not possible right now for the reasons in [this comment](https://github.com/beat-feet/beat-feet/issues/120#issuecomment-1186486290). In the future, `.ogg` may be supported, but other formats would require larger changes to the underlying framework used by this game (libgdx). Though perhaps there is hope in this discussion on the [libgdx issue tracker](https://github.com/libgdx/libgdx/issues/6622) which implies that perhaps the https://github.com/barsoosayque/libgdx-oboe can help.
