### ISSUE TITLE
Disable android's back&home buttons

### ISSUE THREAD

**Issue by Glitchy-Tozier** [beat-feet/beat-feet#68]
Make them disappear, as is done in many other games and fullscreen videos. This could help make the game more immersive as is some android themes that back&home-bar get's really distracting.

((First fix #64 though. I need my back-buttons until this is implemented!!))

**Comment by pserwylo** [comment]
This is good, but will also depend on #73 (add a pause button). By doing so, the user sill still have the option to leave the game. Without it, they'd have to intentionally kill the player in order to get a menu.

**Comment by Glitchy-Tozier** [comment]
Absolutely agree.

**Comment by pserwylo** [comment]
A fix for this has been implemented alongside the fix for #93. The next release will make use of Android ["immersive" (fullscreen) mode](https://developer.android.com/training/system-ui/immersive).
