### ISSUE TITLE
[Bug] Locking the screen distorts level-choosing screen.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [beat-feet/beat-feet#69]
### Steps to reproduce:
1. Go here:
![Screenshot_20210304-085157_beat-game.jpg](https://user-images.githubusercontent.com/59611881/109929629-f9212580-7cc6-11eb-83bb-44192f34207f.jpg)
2. Lock (turn off) screen
3. Unlock your phone
4. See bug:
![Screenshot_20210304-085205_beat-game.jpg](https://user-images.githubusercontent.com/59611881/109929646-fd4d4300-7cc6-11eb-8759-60bd2ee9d3c1.jpg)

This happens on v.2.0, Samsung Galaxy S9

**Comment by pserwylo** [comment]
Thanks for the report and clear reproduction steps. I believe this has been (somewhat inadvertelantly, but a little bit on purpose) in v0.6.0 when the UI was overhauled. 

Please feel free to reopen if you experience this again.
