### ISSUE TITLE
Replay not working

### ISSUE THREAD

**Issue by comradekingu** [beat-feet/beat-feet#86]
Got a 10x bonus on one of the levels, clicked replay.
Starts the level again.

Curiously the button is in a different place from getting a % cleared bonus.

**Comment by pserwylo** [comment]
Thanks for the report, though I must admit I'm a little lost as to the specific issue here. My expectation would be that regardless of what achievements you get, "Replay" should always start the level again. Is this what you are experiencing?

**Comment by comradekingu** [comment]
Ah, my bad. I thought since the menu looked different, it was going to be a replay of the level or the combo.
"Play again" or "Retry" would avoid this for me.

**Comment by pserwylo** [comment]
Right, makes sense. Definitely lets fix this. It should be renamed to "Retry". In my opinion this is better than "Play again" because then the terminology can be shared with the pause screen. If it says "Play again" on the pause screen, perhaps it could be confusing.

**Comment by comradekingu** [comment]
I like "Retry" better too. Doesn't have to be the same for ~"unpause".
See the "Edit:" at the bottom of https://github.com/beat-feet/beat-feet/issues/63#issuecomment-809321746
There is some purity in going for terrible English too. Like a "Jump in level again" type of authentic. ;)

**Comment by pserwylo** [comment]
Okay, I like your last comment of "Doesn't have to be the same for the pause screen". Lets go with:

**Pause screen: "Restart"**

![image](https://user-images.githubusercontent.com/248565/114549168-0822cc80-9ca4-11eb-8c88-0cfc31168da7.png)


**End game screen: "Play Again"**

![image](https://user-images.githubusercontent.com/248565/114549313-30123000-9ca4-11eb-91dc-68306f1b8d34.png)
