### ISSUE TITLE
Player still alive even after death

### ISSUE THREAD

**Issue by Thewisem** [beat-feet/beat-feet#92]
Once the player's hearts are gone, they should die. But I didn't die. Even when my hearts all finished. No matter the shields, once the hearts are lost, game over
![Screenshot_20210508-214148](https://user-images.githubusercontent.com/74511929/117550140-4020f380-b047-11eb-88e2-ba8cf2a79e66.jpg)

**Comment by pserwylo** [comment]
Thanks for the report @Thewisem and great work on catching that screenshot!

This is somewhat expected. Each heart represents 20% of your health, with half hearts worth 10%. Therefore if you are less than 10% then it will show zero hearts (but vigorously shake to hint at the fact that you are very near death).

Regarding shields, you can also build up your shield while you have less than 10% health. Indeed if you are that low, we would encourage it to preserver your life!

As such, I'll close this issue as expected, but please feel free to re-open if I've misunderstood what you are describing.
