### ISSUE TITLE
Pressing back button from game over screen produces overlaid menu.

### ISSUE THREAD

**Issue by vi** [beat-feet/beat-feet#93]
"Paused [Resume] [Restart] [Change Level] [Main menu]" screen is laid atop of "[Play Again] [Change Level] [Main Menu]" game over screen.

Pressing back button while at game over screen should exit to main menu or level selection.

Also maybe repeatedly pressing back button again and again should eventually exit the game, not toggle between paused and unpaused.

**Comment by pserwylo** [comment]
Good catch, thanks for the report.

I've got a fix queued up, will just sort out a couple of other small issues and then bump a new release for F-Droid to build.
