### ISSUE TITLE
Game stopped working after last update (Android 9)

### ISSUE THREAD

**Issue by lionkmp** [beat-feet/beat-feet#97]
Hi guys,
First thanks for the great game, and very good recent improvements!

After one of the most recent updates, it totally does not start up. Just displays the application crashed.
I'm installing from F-Droid, and Motorola Moto X4 phone, running Android 9 (Amazon).
Thanks in advance!

**Comment by pserwylo** [comment]
Thanks for the kind words and the report @lionkmp.

Are you in a position to [obtain a stacktrace from `logcat`](https://developer.android.com/studio/command-line/logcat#Overview) to help understand the crash?

When I install [v0.10.0 from F-Droid](https://f-droid.org/packages/com.serwylo.beatgame/) on a couple of my devices it works as expected.

The only thing I can think of is perhaps the language settings on your phone, given that this was the change introduced in the latest version. Do you mind me asking what languages you have configured in your Android system settings?

**Comment by lionkmp** [comment]
Hi,
This is output "logcat -b crash" based on the link you sent. This appears when I attempt to start the game. The phone is set to Hungarian language, there is no translation yet.

06-01 20:47:22.261 17059 17059 E AndroidRuntime: FATAL EXCEPTION: main
06-01 20:47:22.261 17059 17059 E AndroidRuntime: Process: com.serwylo.beatgame, PID: 17059
06-01 20:47:22.261 17059 17059 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.serwylo.beatgame/com.serwylo.beatgame.AndroidLauncher}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.badlogic.gdx.Application.error(java.lang.String, java.lang.String)' on a null object reference
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6912)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.badlogic.gdx.Application.error(java.lang.String, java.lang.String)' on a null object reference
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at com.serwylo.beatgame.Assets$Companion.getLocale(Assets.kt:314)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at com.serwylo.beatgame.BeatFeetGame.<init>(BeatFeetGame.kt:15)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at com.serwylo.beatgame.AndroidLauncher.onCreate(AndroidLauncher.java:13)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7148)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7139)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
06-01 20:47:22.261 17059 17059 E AndroidRuntime: 	... 11 more

**Comment by pserwylo** [comment]
Oh well that is embarrassing! I've tested it for the languages which *do* have translations, but not for those which *don't*! Let me go fix this up for you.

**Comment by pserwylo** [comment]
Release v0.10.1 tagged, will be picked up by F-Droid in the coming days, keep an eye out and once it is released it would be great to hear if it resolves the issue for you.

Funnily enough, the crash was not actually to do with the translations per-se, that all worked as expected. The issue was purely related to trying to log a friendly message to logcat explaining that the language used by your phone does not have a supported translation in Weblate yet! Fixed it by ensuring that all the logging infrastructure was setup by the framework prior to deciding whether the locale is supported (so we can still log a friendly message).

**Comment by lionkmp** [comment]
So far it's not on F-Droid, but thank you very much for the quick fix. I'll update here when it comes to F-Droid. After that, I plan to translate to Hungarian, but waiting for the test first, to not break the test case.

**Comment by lionkmp** [comment]
Got the update, IT WORKS. Thank you! ;-)

**Comment by pserwylo** [comment]
Ah wonderful, thanks so much for the feedback (as well as the original report). Also, thanks for the offer of translating to Hungarian. It is very close to the top of my todo list to make sure that all languages are fully supported, but you may want to cast an eye over this list of characters first to see if those required by the Hungarian language are in the fonts currently in use?

![Screenshot_2021-06-09_17-49-15](https://user-images.githubusercontent.com/248565/121314859-2119c800-c94b-11eb-898b-d556c82938f8.png)

If not, you should probably wait until I get around to building in support for a broader set of characters (see #90). If that is the case, hope you don't mind me pinging you via GitHub once that is done in case you still want to translate :D

**Comment by lionkmp** [comment]
The link to Screenshot is missing from your post here, but it was in the notification e-mail fortunately.

Two Hungarian letters are missing, ő and ű (with two "commas"), but in the old DOS times we always missed that, and we used what's in the ISO-8895-1 charset in place of those two ISO-8859-2 characters. 

You already have those:

u + ^  (char codes 156, 188 in your Screenshot) Hungarian letters: ű Ű
o + ~  (char codes 150, 182 in your Screenshot) Hungarian letters: ő Ő

(Or at least temporarily if you wish. :) I think Hungarian users would be totally fine with that replacement, older will even feel nostalgic about it. We sometimes still see this replacement.) Yes, it's OK to ping me for this, whichever solution you recommend. :)
